import { actingInstructions, confessions } from './confessions';import { getRoom, saveRoom } from './db';
export type Truth='real'|'fake'|'half'; const truths:Truth[]=['real','fake','half'];
const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString(); const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
export function createRoom(name:string,createPassword:string,roomPassword?:string){if(createPassword!==process.env.CREATE_ROOM_PASSWORD) throw Error('Contraseña global inválida'); const c=code(); const pid=id(); const room={id:id(),code:c,hostPlayerId:pid,status:'lobby',settings:{intensity:'tranqui',roundDuration:45,totalRounds:5},currentRoundIndex:0,usedConfessionIds:[],players:[{id:pid,name,score:0,isConnected:true,joinedAt:now()}],rounds:[],votes:[],roomPassword:roomPassword||null,createdAt:now(),updatedAt:now()}; saveRoom(c,room); return {room,playerId:pid};}
export function joinRoom(code:string,name:string,password?:string){const room=getRoom(code); if(!room) throw Error('Sala no existe'); if(room.roomPassword&&room.roomPassword!==password) throw Error('Contraseña de sala inválida'); if(room.players.length>=7) throw Error('Sala llena'); if(room.players.some((p:any)=>p.name===name)) throw Error('Nombre duplicado'); const p={id:id(),name,score:0,isConnected:true,joinedAt:now()}; room.players.push(p); room.updatedAt=now(); saveRoom(code,room); return {room,playerId:p.id};}
export const getRoomState=(code:string)=>{const room=getRoom(code); if(!room) throw Error('Sala no existe'); if(room.status==='timer'){const r=room.rounds[room.currentRoundIndex]; if(r.startedAt&&Date.now()-Date.parse(r.startedAt)>=r.durationSeconds*1000){room.status='voting';r.status='voting';saveRoom(code,room);} } return getRoom(code);};
export function updateRoom(code:string,fn:(room:any)=>any){const room=getRoom(code); if(!room) throw Error('Sala no existe'); fn(room); room.updatedAt=now(); saveRoom(code,room); return room;}
export function createRound(room:any){const pool=confessions[room.settings.intensity as keyof typeof confessions]; const remaining=pool.map((_,i)=>i).filter(i=>!room.usedConfessionIds.includes(i)); const confIdx=pick(remaining.length?remaining:pool.map((_:any,i:number)=>i)); room.usedConfessionIds.push(confIdx); const unplayed=room.players.filter((p:any)=>!room.rounds.some((r:any)=>r.confessorPlayerId===p.id)); const confessor=pick((unplayed.length?unplayed:room.players).map((p:any)=>p.id)); const round={id:id(),index:room.currentRoundIndex,confessorPlayerId:confessor,confessionId:confIdx,confessionText:pool[confIdx],truthType:pick(truths),actingInstruction:pick(actingInstructions),status:'waiting',startedAt:null,durationSeconds:room.settings.roundDuration}; room.rounds[room.currentRoundIndex]=round;}
