'use client';
import { useMemo, useState } from 'react';import { useRoomPolling } from '@/hooks/useRoomPolling';
const post=(u:string,b:any)=>fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}).then(async r=>{const j=await r.json();if(!r.ok) throw Error(j.error); return j;});
export default function Page(){const [name,setName]=useState('');const [roomCode,setRoomCode]=useState(()=>typeof window!=='undefined'?localStorage.getItem('roomCode')||'':'');const [playerId,setPlayerId]=useState(()=>typeof window!=='undefined'?localStorage.getItem('playerId')||'':'');const [createPassword,setCreatePassword]=useState('');const [joinPass,setJoinPass]=useState('');const [roomPass,setRoomPass]=useState('');const [err,setErr]=useState('');const {room,error}=useRoomPolling(roomCode||null);
const me=useMemo(()=>room?.players?.find((p:any)=>p.id===playerId),[room,playerId]); const round=room?.rounds?.[room?.currentRoundIndex]; const isHost=room?.hostPlayerId===playerId;
const save=(d:any)=>{localStorage.setItem('roomCode',d.room.code);localStorage.setItem('playerId',d.playerId);setRoomCode(d.room.code);setPlayerId(d.playerId)};
if(!roomCode||!playerId) return <main className='p-4 max-w-md mx-auto space-y-4'><h1 className='text-3xl font-bold text-center'>Confesionario Falso</h1><div className='card space-y-3'><input className='w-full p-3 rounded bg-zinc-800' placeholder='Tu nombre' value={name} onChange={e=>setName(e.target.value)}/><input className='w-full p-3 rounded bg-zinc-800' placeholder='Password global crear sala' value={createPassword} onChange={e=>setCreatePassword(e.target.value)}/><input className='w-full p-3 rounded bg-zinc-800' placeholder='Password sala (opcional)' value={roomPass} onChange={e=>setRoomPass(e.target.value)}/><button className='btn bg-fuchsia-600' onClick={async()=>{try{save(await post('/api/rooms/create',{name,createPassword,roomPassword:roomPass||undefined}));}catch(e:any){setErr(e.message);}}}>Crear sala</button><input className='w-full p-3 rounded bg-zinc-800' placeholder='Código sala' value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())}/><input className='w-full p-3 rounded bg-zinc-800' placeholder='Password sala (si tiene)' value={joinPass} onChange={e=>setJoinPass(e.target.value)}/><button className='btn bg-indigo-600' onClick={async()=>{try{save(await post('/api/rooms/join',{name,code:roomCode,roomPassword:joinPass||undefined}));}catch(e:any){setErr(e.message);}}}>Unirme</button>{err&&<p className='text-red-400'>{err}</p>}</div></main>;
if(error) return <main className='p-4'>{error}</main>;
return <main className='p-4 max-w-md mx-auto space-y-4'><div className='card'><p className='text-sm'>Sala</p><p className='text-4xl font-black tracking-widest'>{room.code}</p><p>Host: {room.players.find((p:any)=>p.id===room.hostPlayerId)?.name}</p></div><div className='card'><p>Jugadores ({room.players.length}/7)</p>{room.players.map((p:any)=><p key={p.id}>{p.name} · {p.score}pts</p>)}</div>{room.status==='lobby'&&<div className='card space-y-2'>{isHost&&<><select className='w-full bg-zinc-800 p-2 rounded' onChange={e=>post(`/api/rooms/${room.code}/settings`,{playerId,settings:{...room.settings,intensity:e.target.value}})} defaultValue={room.settings.intensity}><option value='tranqui'>Tranqui</option><option value='picante'>Picante</option><option value='muy_picante'>Muy picante</option></select><select className='w-full bg-zinc-800 p-2 rounded' onChange={e=>post(`/api/rooms/${room.code}/settings`,{playerId,settings:{...room.settings,roundDuration:Number(e.target.value)}})} defaultValue={room.settings.roundDuration}><option>30</option><option>45</option><option>60</option></select><select className='w-full bg-zinc-800 p-2 rounded' onChange={e=>post(`/api/rooms/${room.code}/settings`,{playerId,settings:{...room.settings,totalRounds:Number(e.target.value)}})} defaultValue={room.settings.totalRounds}><option>5</option><option>7</option><option>10</option></select><button className='btn bg-emerald-600' disabled={room.players.length<3} onClick={()=>post(`/api/rooms/${room.code}/start`,{playerId})}>Empezar partida</button></>}{!isHost&&<p>Esperando al host...</p>}{room.players.length<3&&<p>Faltan jugadores</p>}</div>}
{['playing','timer','voting','reveal','finished'].includes(room.status)&&<div className='card space-y-2'><p>Ronda {room.currentRoundIndex+1}/{room.settings.totalRounds}</p><p>Confesor: {room.players.find((p:any)=>p.id===round.confessorPlayerId)?.name}</p><p>Estado: {room.status}</p>{room.status==='timer'&&<p className='text-6xl font-black'>{Math.max(0,round.durationSeconds-Math.floor((Date.now()-Date.parse(round.startedAt))/1000))}</p>}{round.confessorPlayerId===playerId&&room.status!=='reveal'&&<div className='bg-zinc-800 p-3 rounded'><p>{round.confessionText}</p><p>Tipo: {round.truthType}</p><p>{round.actingInstruction}</p></div>}{round.confessorPlayerId!==playerId&&room.status!=='reveal'&&<p>Escuchá la confesión y votá cuando termine.</p>}{isHost&&room.status==='playing'&&<button className='btn bg-amber-500' onClick={()=>post(`/api/rooms/${room.code}/start-timer`,{playerId})}>Empezar timer</button>}{room.status==='voting'&&round.confessorPlayerId!==playerId&&<div className='grid grid-cols-3 gap-2'>{['real','fake','half'].map(v=><button key={v} className='btn bg-indigo-700' onClick={()=>post(`/api/rooms/${room.code}/vote`,{playerId,vote:v})}>{v}</button>)}</div>}{room.status==='voting'&&isHost&&<button className='btn bg-fuchsia-700' onClick={()=>post(`/api/rooms/${room.code}/reveal`,{playerId})}>Revelar</button>}{room.status==='reveal'&&<div><p className='font-bold'>{round.confessionText}</p><p>Era: {round.truthType}</p>{room.votes.filter((v:any)=>v.roundId===round.id).map((v:any)=><p key={v.id}>{room.players.find((p:any)=>p.id===v.playerId)?.name}: {v.vote}</p>)}</div>}{room.status==='reveal'&&isHost&&<button className='btn bg-emerald-700' onClick={()=>post(`/api/rooms/${room.code}/next`,{playerId})}>Siguiente</button>}{room.status==='finished'&&<><p>🏁 Final</p><button className='btn bg-sky-700' onClick={()=>post(`/api/rooms/${room.code}/restart`,{playerId})}>Jugar de nuevo</button></>}</div>}
<button className='btn bg-zinc-700' onClick={()=>{localStorage.clear();location.reload();}}>Salir</button></main>;
}
